// <auto-generated />
namespace Meldpunt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_components_to_pages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_components_to_pages));
        
        string IMigrationMetadata.Id
        {
            get { return "201906240820238_add_components_to_pages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
