// <auto-generated />
namespace Meldpunt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_basepagemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_basepagemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201906250747140_added_basepagemodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
