// <auto-generated />
namespace Meldpunt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class plaatsPages_and_reactions1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(plaatsPages_and_reactions1));
        
        string IMigrationMetadata.Id
        {
            get { return "201905071350556_plaatsPages_and_reactions1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
