// <auto-generated />
namespace Meldpunt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_parentPath_from_page : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_parentPath_from_page));
        
        string IMigrationMetadata.Id
        {
            get { return "201904151409124_remove_parentPath_from_page"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
