// <auto-generated />
namespace Meldpunt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class urlpart_required_for_blog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urlpart_required_for_blog));
        
        string IMigrationMetadata.Id
        {
            get { return "201904080923161_urlpart_required_for_blog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
