// <auto-generated />
namespace Meldpunt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_date_to_redirects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_date_to_redirects));
        
        string IMigrationMetadata.Id
        {
            get { return "201907031338509_add_date_to_redirects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
