// <auto-generated />
namespace Meldpunt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class required_lastmodified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required_lastmodified));
        
        string IMigrationMetadata.Id
        {
            get { return "201906262035218_required_lastmodified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
